-- SynthesisOne: automatic license activation from the first payment SMS.
-- Run this in Supabase SQL Editor before deploying the new backend.

create table if not exists public.license_activation_sessions (
  activation_id text primary key,
  secret_hash text not null,
  phone_number text not null,
  device_id text not null,
  status text not null default 'WAITING_PAYMENT',
  client_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  last_payment_reason text,
  last_bootstrap_at timestamptz
);

create index if not exists idx_license_activation_sessions_phone_device
  on public.license_activation_sessions (phone_number, device_id, status);

create index if not exists idx_license_activation_sessions_status_created
  on public.license_activation_sessions (status, created_at desc);

create table if not exists public.license_payments (
  id bigint generated by default as identity primary key,
  payment_key text not null unique,
  activation_id text not null,
  client_id text,
  sender text,
  body text not null,
  received_at timestamptz not null,
  parsed jsonb,
  amount numeric,
  currency text,
  transaction_id text,
  status text not null,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists idx_license_payments_activation
  on public.license_payments (activation_id, created_at desc);

create index if not exists idx_license_payments_status
  on public.license_payments (status, created_at desc);

create index if not exists idx_license_payments_transaction
  on public.license_payments (transaction_id);

-- Optional safety: only allow known lifecycle values.
-- If your existing environment already has rows with other values, inspect first.
-- alter table public.license_activation_sessions
--   add constraint license_activation_status_chk
--   check (status in ('WAITING_PAYMENT','ACTIVATED','EXPIRED'));

-- RLS is intentionally not enabled here because the server uses the Supabase
-- service-role key. Do not expose service-role credentials to the Android app.
