-- SynthesisOne: reliable, idempotent and signed webhook delivery.
-- Run after 005_prevent_duplicate_active_clients.sql when applicable.

create extension if not exists pgcrypto;

-- Existing clients created before webhook_secret became standard receive a
-- cryptographically random secret. Webhook consumers can read it from the
-- authenticated admin panel/details endpoint, not from client-facing APIs.
update public.clients
set webhook_secret = encode(gen_random_bytes(32), 'hex')
where (webhook_secret is null or btrim(webhook_secret) = '')
  and role = 'client';

create table if not exists public.webhook_deliveries (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  event_id text not null,
  sms_log_id text,
  webhook_url text not null,
  payload jsonb not null,
  status text not null default 'PENDING',
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  response_status integer,
  response_body text,
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create unique index if not exists webhook_deliveries_client_event_url_uq
  on public.webhook_deliveries (client_id, event_id, webhook_url);

create index if not exists webhook_deliveries_pending_idx
  on public.webhook_deliveries (status, next_attempt_at, created_at);

create index if not exists webhook_deliveries_client_idx
  on public.webhook_deliveries (client_id, created_at desc);

create index if not exists webhook_deliveries_event_idx
  on public.webhook_deliveries (event_id);

-- Keep lifecycle values predictable without breaking existing data.
-- Existing invalid values, if any, must be inspected before adding this check.
-- alter table public.webhook_deliveries
--   add constraint webhook_deliveries_status_chk
--   check (status in ('PENDING','DELIVERING','DELIVERED','FAILED'));

comment on table public.webhook_deliveries is 'Outbox durable para entrega de webhooks de SMS/transacciones con reintentos e idempotencia.';
comment on column public.webhook_deliveries.event_id is 'Identificador determinista del evento. Un mismo SMS no crea dos entregas para la misma URL.';
comment on column public.webhook_deliveries.payload is 'Payload JSON firmado al momento de la entrega; nunca incluye token del cliente ni webhook_secret.';
