-- Durable webhook observability. Never store secrets, tokens or Authorization headers.
create table if not exists public.webhook_event_logs (
  id bigint generated by default as identity primary key,
  client_id uuid,
  event_id text,
  delivery_id bigint,
  event text not null default 'UNKNOWN',
  level text not null default 'INFO',
  status text,
  stage text,
  webhook_url text,
  attempt integer,
  response_status integer,
  response_body text,
  error text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists webhook_event_logs_client_idx on public.webhook_event_logs(client_id, created_at desc);
create index if not exists webhook_event_logs_event_idx on public.webhook_event_logs(event_id, created_at desc);
create index if not exists webhook_event_logs_delivery_idx on public.webhook_event_logs(delivery_id, created_at desc);
comment on table public.webhook_event_logs is 'Auditoría detallada del ciclo de vida de los webhooks: cola, intento, respuesta, error y reintentos. No contiene secretos.';
